WIP. Attempt to fix Github Actions issue with GLIBC
GH Actions is repeatedly failing today for reasons I don’t understand.
Re-running the jobs sometimes works, sometimes doesn’t. Hopefully this
stabilizes it.

----
error: failed to run custom build command for `proc-macro2 v1.0.95`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_TEST_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `/home/runner/work/crc-fast-rust/crc-fast-rust/target/debug/build/proc-macro2-566bea0d21b824a5/build-script-build` (exit status: 1)
  --- stderr
  /home/runner/work/crc-fast-rust/crc-fast-rust/target/debug/build/proc-macro2-566bea0d21b824a5/build-script-build: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.39' not found (required by /home/runner/work/crc-fast-rust/crc-fast-rust/target/debug/build/proc-macro2-566bea0d21b824a5/build-script-build)
warning: build failed, waiting for other jobs to finish...
----